name: soma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0

  
  image_picker: ^1.1.2
  image_cropper: ^9.1.0 # Updated for image cropping
  emoji_picker_flutter: ^4.3.0
  flutter_keyboard_visibility: ^6.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  build_test: ^2.2.2
  logger: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/landing_page_hero1.jpg
    - assets/images/google_logo.png
    - assets/images/default_thumbnail.jpg

  fonts:
    - family: PlaywriteQLD
      fonts:
        - asset: assets/google_fonts/static/PlaywriteAUQLD-Regular.ttf